script: npm run build
language: node_js
node_js:
- '8'
env:
- BUILD_ENV=CI
cache:
  directories:
  - node_modules
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
deploy:
- provider: releases
  api_key:
    secure: WTY2eMUrgVap7b1w/O48TGHBZ6cYoBHPAGKZZ2dw3A1JpPZnZcxuUNoEAdJi58W1XJ5kOG89NVlS/OZHBy8w74Nhfq90sOeEwbb9jiV5gHPunxeKL5qO+iW6ufquCq/uJ0WF6j5aqNrNwXvp/DFOqjRXdyjsqxnIwqdETM6mLKOT48PS0wxcZkbnnCDKCQPhorg8JpImrww7emHEoz9McvZM9DI7zmod5575svpt9bw4ZWABdjeVnqmI+S2ANwJjpSkG7L5b21Me/H5KKMQ35ZSO+o+MmIAfpWSMyxbI/L/dDuwfIDt7LeiJFeQuzQ9NNH5BIrwgZ57oE+05Py9b0BBFLIHRKue6+oFvCYelwYejMlYqY8NBoXbudkZUVHshWt9XeYjSxeD3CZsfgSaD0e13+LU0hWiZ+G7dwhp/HApvrXnpBDbBnAmW0sTraEaRkpRP07mCGO2fDM5X3UtSHIWu40BLnpcGTqjTzWrZIVIRXPLAIkDw7+KL1pf7dCb6rVRMYEbkl7Txv61B2KT/TytXaESZIhAYJBrK05JNdvDygsC7bovNOAPKoev6yrilJEJCXG63wLY6nVM7WJuhe2eD+3PSlJFc3pr1sZ6X6sPD2pKi1krvrscXEcf8V/a2Zkfl8BiRR+sHDPO4IEYge7B7upL57C8B0iaXPgyCLAw=
  file:
    - dist/ef.min.js
    - dist/ef.min.js.map
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: syqlds@126.com
  api_key:
    secure: bhJPpDfQErKC3L4YWeGol+w42arwqUrs29nXL96tHS/IzX+3iumQHkeAMa3WWxX5qpVWanq+h7ZaxxktP3qi+81PYKYw3wXaw6dGqU+XHwdOAu0bVC7aQW3iu+FOo9wPja4j2ViyANu2C79pmON5uaTAauMdOLrB4Sfd7gribftRMaDb09WehV2W+5C6MXShsYs23d8fD+mCpdlw5uNd4NDAzoVmphDEyfA9PkEX79inLqdS0xyYLPsDYqpAyzJbkvgS3Gz+HNa6MDfP2oC8rPyA3wAq8oDNT+Ip/dWns42Q1Ls5HqENbRyR8HfWP/2P4+CAHV3I1LP4aG7iEUH8fMOlx8EaiqcY0YzJlTh7IeDpCmnioegs2QyfGSis1G8N2RtB2RWcpEx+dULCYKFgyMCMlujSH3YKkIJOWAnnXUXeG5PzsSOmUckaIbAdPf+0qYwkvwSNgEkQ5jZ8b46qDmGgr1GyrGQWRvB3KqmYiwa1IO5RMuujNf5IQ2vnAbSCmsMWN8lshvL0kEKrVB1KXsT9RKhSDUaJrcyEe/zmIdwJfTzXGstRyxgVKHFP74qIsCtpKNExtDa5b31bMscswME8kWQ8Ur6wmtii2qcWIclQB97hwwtPrhypoZwF8O9IxVxmhZxTXjlDkL6C69JtuG/uc6h3xHf4SE6SzqoShvo=
  skip_cleanup: true
  on:
    branch: master
